export EDITOR=nvim
export VISUAL=nvim
export GIT_EDITOR=nvim

alias vi='nvim'
alias vim='nvim'
alias lg='lazygit'
alias ls='ls --color=auto'
alias ll='ls -alF'
alias l='ll'
alias s='ls'

if command -v starship >/dev/null 2>&1; then
    eval "$(starship init bash)"
fi
