export EDITOR=nvim
export VISUAL=nvim
export GIT_EDITOR=nvim

alias vi='nvim'
alias vim='nvim'
alias lg='lazygit'
alias ls='ls --color=auto'
alias ll='ls -alF'
alias l='ll'
alias s='ls'

# Keep zsh line editing close to the default macOS shell experience.
bindkey -e
bindkey '^P' up-line-or-history
bindkey '^N' down-line-or-history
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line
bindkey '^B' backward-char
bindkey '^F' forward-char
bindkey '^[b' backward-word
bindkey '^[f' forward-word
bindkey '^?' backward-delete-char
bindkey '^H' backward-delete-char
bindkey '^[[3~' delete-char
bindkey '^W' backward-kill-word
bindkey '^U' backward-kill-line
bindkey '^K' kill-line
bindkey '^Y' yank
bindkey '^R' history-incremental-search-backward
bindkey '^[.' insert-last-word
bindkey '^L' clear-screen
bindkey '^_' undo
bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line
bindkey '^[[1~' beginning-of-line
bindkey '^[[4~' end-of-line
bindkey '^[[7~' beginning-of-line
bindkey '^[[8~' end-of-line

if command -v starship >/dev/null 2>&1; then
    eval "$(starship init zsh)"
fi
